### ISSUE TITLE
Resolving multiple extensions in documents 

### ISSUE THREAD

**Issue by ThisIsMissEm** [swicg/extensions-policy#12]
Currently the document says:

>  If the publisher uses different extensions in the same document with different terms, they will need to resolve those naming conflicts by hand. 

I think this should actually read as follows, emphasis for changed word:

>  If the publisher uses different extensions in the same document with **the same** terms, they will need to resolve those naming conflicts by hand.

And I think the example should read as:

```json
{
    "@context": [
        "https://www.w3.org/ns/activitystreams",
        {"ic": "https://favorites.example/ns/icecream" }, 
        { "horse": "https://horse.example/ns/colors" }
    ],
    "id": "https://example.com/people/evan",
    "type": "Person",
    "name": "Evan Prodromou",
    "favoriteIceCreamFlavor": "ic:Chocolate",
    "horseCoatColor": "horse:Chocolate"
}
```

That is, the context values need names/identifiers to distinguish between the two `Chocolate` terms. 

Though I'm also wondering if `favoriteIceCreamFlavor` and `horseCoatColor` should be prefix too? i.e., `ic:favoriteIceCreamFlavor` and `horse:coatColor`? I'm not sure there.

**Comment by nightpool** [comment]
correct, if your context defines "ic" as short for "
https://favorites.example/ns/icecream", then your term needs to read
"ic:favoriteIceCreamFlavor"

**Comment by evanp** [comment]
So, I resolved `different` and `the same`. Thanks for the note!

I'm moving the question about the example to a different issue.
